<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<title>Programmieren 2 - Kapitel 4 - Exception-Handling</title>

		<link rel="stylesheet" href="reveal.js/css/reset.css">
		<link rel="stylesheet" href="reveal.js/css/reveal.css">

        <link rel="stylesheet" href="src/slides.css">
        <link rel="stylesheet" href="src/style.css">

		<link rel="stylesheet" href="src/layout.css">
        <link rel="stylesheet" href="lib/joint.min.css" />
        <link rel="stylesheet" href="src/erd.css" />
        <link rel="stylesheet" href="poll/poll.css" />

		<!-- Theme used for syntax highlighting of code -->
		<link rel="stylesheet" href="src/rainbow.css">

        <!--<script defer src="lib/fontawesome.all.min.js"/>-->
        <link href="lib/fontawesome.all.min.css" rel="stylesheet">
        <style> .reveal i.fa { font-family:FontAwesome; font-style: normal; } </style>

		<!-- Printing and PDF exports -->
		<script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'reveal.js/css/print/pdf.css' : 'reveal.js/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>
	</head>
	<body>
		<div class="reveal">
            <div id="header"></div>
            <div id="footer"></div>
			<div class="slides">
                <section>
                    <h4 style="text-align:center"><b>Prof. Dr.-Ing. Johannes Schildgen</b><br>
                    <a href="mailto:johannes.schildgen@h-da.de">johannes.schildgen@oth-regensburg.de</a></h4>
                    <h1 style="font-size: 240%;">Programmieren 2 (Java)</h1>
                    <h3>Kapitel 4: Exception-Handling</h3>
                    <h4 style="text-align:center">2020-05-13</h4>
                    <img src="img/ccby.png" height="60px" style="position: absolute; left:0px; border:0; bottom:-225px;">
                    <img src="img/oth.png" height="60px" style="position: absolute; right:0px; border:0; bottom:-225px; box-shadow:none">
                </section>
                
                <section>
                  <h2>Exceptions</h2>
                  <p class="small">Exceptions werden geworfen, wenn eine Ausnahmesituation auftritt.</p>
                  <pre><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/ExceptionBeispiel.java#5'></code></pre>
                  <p class="fragment small red">java.lang.NumberFormatException: For input string: "500 EUR"</p>
                  <pre class="fragment"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/ExceptionBeispiel.java#7-8'></code></pre>
                  <p class="fragment small red">java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7</p>
                  <div class="fragment">
                    <h4>Catch-or-Throw-Regel</h4>
                    <ul class="small">
                      <li>Entweder man fängt die Exception ab (<code>catch</code>)</li>
                      <li>oder man wirft sie an den Aufrufer weiter (<code>throw</code>).</li>
                    </ul>
                  </div>
                  <aside class="notes">Im obigen Beispiel ist die <code>parseInt</code>-Methode aufgrund ungültiger Zeichen (&quot; EUR&quot;) nicht in der Lage, den String in eine Zahl zu wandeln. Daher wirft die Methode eine <code>NumberFormatException</code>. Im zweiten Beispiel geht der Index im <code>tage</code>-Array von 0 bis 6. Der Zugriff auf <code>tage[7]</code> wirft deshalb die Exception.</aside>
                </section>

                

                <section>
                  <h3>Beispiel: Inhalt einer Datei lesen</h3>
                  <pre><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesen.java#14,16-25,27'></code></pre>
                  
                  <div class="fragment">
                  <ul class="small">
                    <li><code>new FileReader</code> kann eine <code>FileNotFoundException</code> werfen</li>
                    <li><code>BufferedReader.readLine()</code> kann eine <code>IOException</code> werfen</li>
                  </ul>
                  <p class="small" style="margin-left:2cm">&Rightarrow; entweder abfangen oder weiterwerfen!</p>
                  </div>
                  <aside class="notes">IDEs wie IntelliJ zeigen an, welche Exceptions behandelt werden müssen. Das hier gezeigte Programm kann nicht kompiliert werden, bevor man sich um die Behandlung der beiden Exceptions kümmert. </aside>
                </section>

                <section>
                  <h2><code>try catch</code></h2>
                  <div class="columns">
                    <div>
                      <p class="small">Wird im <code>try</code>-Block die abzufangene Exception geworfen,<br>wird sofort in den entsprechenden <code>catch</code>-Block gesprungen.</p>
                    </div>
                    <div>
                      <pre style="width:6cm;"><code class="java" contenteditable data-trim>
                        try {
                          ...
                        } catch (...) {
    
                        }
                      </code></pre>
                    </div>
                  </div>
                  
                  <pre class="fragment"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenTryCatch.java#11-16'></code></pre>

                  <aside class="notes">Die Catch-or-Throw-Regel besagt, dass Exceptions entweder abgefangen werden müssen oder man gibt sie an den Methoden-Aufrufer weiter. Das Abfangen erfolgt in Java mit einem <code>try</code>/<code>catch</code>-Konstrukt. Tritt im gezeigten Beispiel im <code>try</code>-Block eine <code>FileNotFoundException</code> auf, springt das Programm in den entsprechenden <code>catch</code>-Block. Die Exception wurde also behandelt. Das Programm geht weiter.</aside>
                </section>

                <section>
                  <h2><code>try catch</code></h2>
                  <p class="small">Abfangen verschiedener Exceptions:</p>
                  <pre><code style="max-height: 12cm" class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenTryCatch.java#21-35'></code></pre>
                  <aside class="notes">Mehrere <code>catch</code>-Blöcke können verwendet werden, um unterschiedliche Arten von Exceptions unterschiedlich zu behandeln.</aside>
                </section>

                <section>
                  <h2><code>try catch</code></h2>
                  <p class="small">Multi-Catch:</p>
                  <pre style="width: 98%;"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenTryCatch.java#49-52'></code></pre>
                  <div class="fragment">  
                    <p class="small">Abfangen aller Exceptions:</p>
                    <pre style="width: 98%;"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenTryCatch.java#56-59'></code></pre>
                  </div>
                  <aside class="notes">In einem <code>catch</code>-Ausdruck lassen sich mehrere Exceptions mit einem senkrechten Strich <code>|</code> trennen. Das untere Beispiel zeigt, dass es auch möglich ist, jegliche Art von Exception abzufangen und sie auf gleiche Weise zu behandeln. Im oberen Beispiel haben wir nicht wie auf der vorherigen Folie die <code>FileNotFoundException</code> verwendet, da diese eine Subklasse von <code>IOException</code> ist und daher ohnehin schon abgefangen wird.</aside>
                  </section>

                  <section>
                    <h2><code>try catch finally</code></h2>
                    <p class="small">Der <code>finally</code>-Block wird in jedem Falle aufgerufen, egal ob der <code>try</code>-Block mit oder ohne Exception durchlaufen wurde.</p>
                    <pre><code class="java" contenteditable data-trim>
                      try {
                        ...
                      } catch( ... ) {
                        ...
                      } finally {
                        // Aufräumarbeiten (z. B. Datei schließen)
                      }
                    </code></pre>
                    <p class="small">Der <code>finally</code>-Block wird selbst dann noch aufgerufen, wenn im <code>try</code>-Block die Methode, Schleife, etc. mit <code>return</code>, <code>break</code> oder <code>continue</code> verlassen wurde.</p>
                  </section>

                  <section>
                    <h2><code>try catch finally</code></h2>
                    <pre style="width: 98%;"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenTryCatch.java#72-84'></code></pre>
                    <aside class="notes">Das im <code>finally</code>-Block befindliche <code>br.close();</code> wird in jedem Fall ausgeführt, egal ob die Datei fehlerfrei ausgegeben werden konnte oder aus der Methode gesprungen wird, weil dabei ein Fehler auftrat. Da die <code>close</code>-Methode ebenfalls wieder eine <code>IOException</code> werfen kann, wird diese hier abgefangen und ignoriert.</aside>
                  </section>

                  <section>
                    <h3><code>try(...)</code> mit Ressourcen</h3>
                    <p class="small">Deklariert man im <code>try</code>-Statement eine oder mehrere Ressourcen, kümmert sich Java darum, diese am Ende des <code>try</code>-Statements zu schließen, egal ob eine Exception auftrat oder nicht.</p>
                    <pre style="width: 98%;"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenTryCatch.java#90-98'></code></pre>
                    <aside class="notes">Mit einer Ressource ist ein Objekt gemeint, welches nach der Verwendung ordnungsgemäß geschlossen werden soll, z. B. eine Datei oder eine Verbindung zu einer Datenbank. Es können alle Objekte von Klassen verwendet werden, die die Schnittstelle <code>AutoCloseable</code> implementieren. Java ruft dann nach Beendigung des <code>try</code>-Statements deren <code>close()</code>-Methode auf.</aside>
                  </section>

                <section>
                  <h2><code>throws</code></h2>
                  <p class="small">Wenn eine Exception nicht abgefangen wird, wird sie weitergeworfen.</p>
                  <pre style="width: 97%;"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenThrows.java#13-24'></code></pre>
                  

                  <div class="poll fragment" style="bottom:-120px"> 
                    <h1>Wo wird jetzt die IOException abgefangen?</h1>
                        <ul>
                          <li>Wird nun automatisch abgefangen und ignoriert</li>
                          <li data-poll="correct">Muss nun dort abgefangen werden, wo die Methode printDatei augerufen wird</li>
                          <li>Muss nun in der Klasse FileReader abgefangen werden</li>
                          <li>Im Code-Beispiel fehlt try/catch</li>
                        </ul>
                      <h2>https://frage.space</h2>
                     </div>

                  <aside class="notes">Hat die Methode eine <code>throws</code>-Klausel, zeigt dies, dass bei einem Methodenaufruf möglicherweise die genannte Exception geworfen wird. Jemand, der die Methode aufruft, muss sich gemäß der Catch-or-Throw-Regel darum kümmern, diese Exception entweder abzufangen oder ebenfalls weiterzuwerfen.</aside>
                </section>

                <section>
                  <h2><code>throw</code></h2>
                  <p class="small">Manuelles Werfen von Exceptions:</p>
                    <pre style="width: 97%;"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenThrows.java#29-32'></code></pre>
                  <pre class="fragment" style="width: 97%;"><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenThrows.java#39'></code></pre>
                  <aside class="notes">Durch einen Aufruf des <code>throw</code>-Befehl wird die Ausführung der aktuellen Methoden sofort abgebrochen und die gegebene Exception geworfen. Obiges Beispiel wirft einfach die <code>Exception e</code>, die gerade abgefangen wurde, weiter. Im unteren Beispiel wird ein neues <code>Exception</code>-Objekt erzeugt.</aside>
                </section>

                <section>
                  <h2>Eigene Exceptions</h2>
                  <pre><code class="java" contenteditable data-sample-indent="keep" data-sample='code/Programmieren2/src/de/othr/exceptions/MeineEigeneException.java#3-7'></code></pre>
                  <pre><code class="java" contenteditable data-sample='code/Programmieren2/src/de/othr/exceptions/DateiLesenThrows.java#47'></code></pre>
                  <aside class="notes">Gerne darf und soll man die Java-eigenen Exceptions verwenden und werfen, z. B. die <code>IllegalArgumentException</code>, die sich immer dann anbietet, wenn einer Methode ungültige Parameterwerte übergeben wurden. Man kann jedoch auch eigene Exceptions entwickeln, indem man Subklassen der <code>Exceptions</code>-Klasse erstellt.</aside>
                </section>

                <section>
                  <h2><code>Exception</code>-Klasse</h2>
                  <img style="max-height: 10.5cm; margin-top: -8mm;" uml="
                  hide empty members
                  set namespaceSeparator none

                  class Throwable {
                    --
                    + getMessage() : String
                    + printStackTrace()
                    ...
                  }
                  class Error
                  class Exception
                  Throwable <|-- Error
                  Throwable <|-- Exception

                  class RuntimeException
                  class IOException     
                  class &quot;...&quot; as dots1             
                  Exception <|-- RuntimeException
                  Exception <|-- IOException
                  Exception <|-- dots1

                  class ArithmeticException
                  class IllegalArgumentException
                  class &quot;...&quot; as dots2
                  RuntimeException <|-- ArithmeticException
                  RuntimeException <|-- IllegalArgumentException
                  RuntimeException <|-- dots2

                  class FileNotFoundException
                  class &quot;...&quot; as dots3
                  IOException <|-- FileNotFoundException
                  IOException <|-- dots3


                      "/>
                <aside class="notes">Alle Exceptions sind Subklassen der <code>Throwable</code>-Klasse, welche Methoden wie <code>getMessage</code> und <code>printStackTrace</code> bereitstellt. Erstere liefert die Fehlermeldung als String, zweitere gibt den Verlauf über die Ursache der Exception aus. <code>Error</code> sind schwerwiegende Fehler, die i. d. R. nicht behandelt werden müssen. <code>RuntimeException</code>s müssen ebenfalls nicht behandelt werden. Bei allen anderen <code>Exception</code>s gilt die Catch-or-Throw-Regel.</aside>
                </section>

                <section>
                  <h3>Errors, RuntimeExceptions und Co.</h3>
                  <h4><code>Error</code></h4>
                  <ul class="small" style="margin-top: -2mm;">
                    <li>Schwerwiegende Fehler, z. B. <code>OutOfMemoryError</code></li>
                    <li>Empfehlung: Nicht behandeln, Programm abstürzen lassen</li>
                  </ul>
                  <p></p>
                  
                  <div class="fragment">
                    <h4><code>Exception</code> (außer <code>RuntimeException</code>)</h4>
                    <ul class="small" style="margin-top: -2mm;">
                      <li>Muss entweder mit <code>try</code>/<code>catch</code> abgefangen werden</li>
                      <li>oder die Methode muss sie mittels <code>throws</code> weiterwerfen.</li>
                    </ul>
                  </div>
                  <p></p>

                  <div class="fragment">
                    <h4><code>RuntimeException</code></h4>
                    <ul class="small" style="margin-top: -2mm;">
                      <li>Für diese Exceptions gilt die Catch-or-Throw-Regel nicht</li>
                      <li>Kann man abfangen, muss man aber nicht</li>
                      <li>Werden auch ohne <code>throws</code>-Deklaration weitergeworfen</li>
                    </ul>
                  </div>

                  <img style="max-height: 6cm; position: absolute; top:2.5cm; right:5mm" uml="
                  hide empty members
                  set namespaceSeparator none

                  class Throwable
                  class Error
                  class Exception
                  Throwable <|-- Error
                  Throwable <|-- Exception

                  class RuntimeException
                  Exception <|-- RuntimeException
                      "/>

                </section>

                <section>
                  <h2>Kapitelzusammenfassung</h2>
                  <ul>
                    <li>Exceptions, RuntimeExceptions</li>
                    <li>Catch-or-Throw-Regel</li>
                    <li><code>try catch</code></li>
                    <li><code>try catch finally</code></li>
                    <li><code>throws</code> / <code>throw</code></li>
                  </ul>
          </section>

              </div>
            </div>
        
            <script src="reveal.js/js/reveal.js"></script>
                <script src="lib/jquery.js"></script>
                <script src="lib/lodash.js"></script>
                <script src="lib/backbone.js"></script>
                <script src="lib/joint.min.js"></script>
                <script src="lib/deflate.js"></script>
        
            <script src="src/init_reveal.js"></script>
        
                <script>
                if(window.location.search.match( /print-pdf/gi )) {
                        document.getElementById('header').style="display:none";
                        document.getElementById('footer').style="display:none";
                }
                </script>
        
        
          </body>
        </html>
        